namespace SafeStringGenerator.Editor.Generation
{
    internal static class GeneratedCode
    {
        internal const string OwnershipMarker = "// Generated by SafeStringGenerator. Do not edit.";
        internal const string Header = "// <auto-generated>\n" + OwnershipMarker + "\n// </auto-generated>\n\n";
        internal const string Namespace = "SafeStringGenerator.Generated";
    }
}
